/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppQueueRouteImport } from './routes/_app/queue'
import { Route as AppReposRouteImport } from './routes/_app/repos'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppGatesGateIdRouteImport } from './routes/_app/gates/$gateId'
import { Route as AppRunsIndexRouteImport } from './routes/_app/runs/index'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs/$runId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRoute = AppReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGatesGateIdRoute = AppGatesGateIdRouteImport.update({
  id: '/gates/$gateId',
  path: '/gates/$gateId',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/inbox': typeof AppInboxRoute
  '/queue': typeof AppQueueRoute
  '/repos': typeof AppReposRoute
  '/settings': typeof AppSettingsRoute
  '/gates/$gateId': typeof AppGatesGateIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/runs/': typeof AppRunsIndexRoute
}
export interface FileRoutesByTo {
  '/inbox': typeof AppInboxRoute
  '/queue': typeof AppQueueRoute
  '/repos': typeof AppReposRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/gates/$gateId': typeof AppGatesGateIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/runs': typeof AppRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/inbox': typeof AppInboxRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/repos': typeof AppReposRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/gates/$gateId': typeof AppGatesGateIdRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/_app/runs/': typeof AppRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/queue'
    | '/repos'
    | '/settings'
    | '/gates/$gateId'
    | '/runs/$runId'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/inbox'
    | '/queue'
    | '/repos'
    | '/settings'
    | '/'
    | '/gates/$gateId'
    | '/runs/$runId'
    | '/runs'
  id:
    | '__root__'
    | '/_app'
    | '/_app/inbox'
    | '/_app/queue'
    | '/_app/repos'
    | '/_app/settings'
    | '/_app/'
    | '/_app/gates/$gateId'
    | '/_app/runs/$runId'
    | '/_app/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos': {
      id: '/_app/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AppReposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gates/$gateId': {
      id: '/_app/gates/$gateId'
      path: '/gates/$gateId'
      fullPath: '/gates/$gateId'
      preLoaderRoute: typeof AppGatesGateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/': {
      id: '/_app/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReposRoute: typeof AppReposRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGatesGateIdRoute: typeof AppGatesGateIdRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRoute,
  AppQueueRoute: AppQueueRoute,
  AppReposRoute: AppReposRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGatesGateIdRoute: AppGatesGateIdRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
