/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GatesGateIdRouteImport } from './routes/gates/$gateId'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesGateIdRoute = GatesGateIdRouteImport.update({
  id: '/gates/$gateId',
  path: '/gates/$gateId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/gates/$gateId': typeof GatesGateIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/gates/$gateId': typeof GatesGateIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repos': typeof ReposRoute
  '/settings': typeof SettingsRoute
  '/gates/$gateId': typeof GatesGateIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/repos' | '/settings' | '/gates/$gateId' | '/runs/$runId' | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repos' | '/settings' | '/gates/$gateId' | '/runs/$runId' | '/runs'
  id:
    | '__root__'
    | '/'
    | '/repos'
    | '/settings'
    | '/gates/$gateId'
    | '/runs/$runId'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReposRoute: typeof ReposRoute
  SettingsRoute: typeof SettingsRoute
  GatesGateIdRoute: typeof GatesGateIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates/$gateId': {
      id: '/gates/$gateId'
      path: '/gates/$gateId'
      fullPath: '/gates/$gateId'
      preLoaderRoute: typeof GatesGateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReposRoute: ReposRoute,
  SettingsRoute: SettingsRoute,
  GatesGateIdRoute: GatesGateIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
